agent: tonic.tensorflow.agents.A2C()
environment: tonic.environments.ControlSuite('swimmer-swimmer15')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 8
sequential: 1
trainer: tonic.Trainer()
