agent: tonic.tensorflow.agents.PPO()
environment: tonic.environments.ControlSuite('walker-stand')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 9
sequential: 1
trainer: tonic.Trainer()
