agent: tonic.tensorflow.agents.TRPO()
environment: tonic.environments.ControlSuite('manipulator-bring_peg')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 1
sequential: 1
trainer: tonic.Trainer()
