agent: tonic.tensorflow.agents.TRPO()
environment: tonic.environments.ControlSuite('manipulator-bring_ball')
header: import tonic.tensorflow
name: null
parallel: 1
seed: 8
sequential: 1
trainer: tonic.Trainer(steps=5000000, epoch_steps=50000, save_steps=500000, test_episodes=5,
  show_progress=False)
