after_training: null
agent: tonic.tensorflow.agents.MPO()
before_training: null
environment: tonic.environments.ControlSuite('hopper-hop')
header: import tonic.tensorflow
name: null
parallel: 1
seed: 9
sequential: 1
trainer: tonic.Trainer(steps=5000000, epoch_steps=50000, save_steps=5000000, test_episodes=5,
  show_progress=False)
