agent: tonic.tensorflow.agents.A2C()
environment: tonic.environments.Bullet('HalfCheetahBulletEnv-v0')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 0
sequential: 1
trainer: tonic.Trainer()
