agent: tonic.tensorflow.agents.DDPG()
environment: tonic.environments.Bullet('InvertedPendulumSwingupBulletEnv-v0')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 8
sequential: 1
trainer: tonic.Trainer()
