agent: tonic.tensorflow.agents.DDPG()
environment: tonic.environments.ControlSuite('finger-turn_easy')
header: import tonic.tensorflow
name: null
parallel: 1
seed: 7
sequential: 1
trainer: tonic.Trainer(steps=5000000, epoch_steps=50000, save_steps=500000, test_episodes=5,
  show_progress=False)
