agent: tonic.tensorflow.agents.TD3()
environment: tonic.environments.ControlSuite('hopper-stand')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 2
sequential: 1
trainer: tonic.Trainer()
