agent: tonic.tensorflow.agents.SAC()
environment: tonic.environments.ControlSuite('acrobot-swingup_sparse')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 1
sequential: 1
trainer: tonic.Trainer()
