agent: tonic.tensorflow.agents.SAC()
environment: tonic.environments.Bullet('InvertedPendulumBulletEnv-v0')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 0
sequential: 1
trainer: tonic.Trainer()
