agent: tonic.tensorflow.agents.TRPO()
environment: tonic.environments.ControlSuite('pendulum-swingup')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 8
sequential: 1
trainer: tonic.Trainer()
