agent: tonic.tensorflow.agents.TRPO()
environment: tonic.environments.ControlSuite('cartpole-swingup_sparse')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 5
sequential: 1
trainer: tonic.Trainer()
