agent: tonic.tensorflow.agents.TD3()
environment: tonic.environments.ControlSuite('walker-walk')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 9
sequential: 1
trainer: tonic.Trainer()
