agent: tonic.tensorflow.agents.DDPG()
environment: tonic.environments.Bullet('HalfCheetahBulletEnv-v0')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 3
sequential: 1
trainer: tonic.Trainer()
