agent: tonic.tensorflow.agents.A2C()
environment: tonic.environments.ControlSuite('ball_in_cup-catch')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 1
sequential: 1
trainer: tonic.Trainer()
