agent: tonic.tensorflow.agents.SAC()
environment: tonic.environments.Gym('HalfCheetah-v3')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 5
sequential: 1
trainer: tonic.Trainer()
