agent: tonic.tensorflow.agents.DDPG()
environment: tonic.environments.Gym('HumanoidStandup-v2')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 1
sequential: 1
trainer: tonic.Trainer()
