agent: tonic.tensorflow.agents.DDPG()
environment: tonic.environments.ControlSuite('stacker-stack_4')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 0
sequential: 1
trainer: tonic.Trainer()
