agent: tonic.tensorflow.agents.SAC()
environment: tonic.environments.ControlSuite('finger-turn_hard')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 7
sequential: 1
trainer: tonic.Trainer()
