agent: tonic.tensorflow.agents.PPO()
environment: tonic.environments.ControlSuite('finger-spin')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 5
sequential: 1
trainer: tonic.Trainer()
