agent: tonic.tensorflow.agents.PPO()
environment: tonic.environments.Gym('Pendulum-v0')
header: import tonic.tensorflow
name: null
parallel: 1
seed: 4
sequential: 1
trainer: tonic.Trainer(steps=5000000, epoch_steps=50000, save_steps=500000, test_episodes=5,
  show_progress=False)
