agent: tonic.tensorflow.agents.DDPG()
environment: tonic.environments.Gym('Hopper-v3')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 3
sequential: 1
trainer: tonic.Trainer()
