agent: tonic.tensorflow.agents.A2C()
environment: tonic.environments.ControlSuite('quadruped-walk')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 4
sequential: 1
trainer: tonic.Trainer()
