agent: tonic.tensorflow.agents.TD3()
environment: tonic.environments.ControlSuite('acrobot-swingup_sparse')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 8
sequential: 1
trainer: tonic.Trainer()
