agent: tonic.tensorflow.agents.TRPO()
environment: tonic.environments.ControlSuite('quadruped-escape')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 9
sequential: 1
trainer: tonic.Trainer()
