agent: tonic.tensorflow.agents.TRPO()
environment: tonic.environments.ControlSuite('walker-run')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 4
sequential: 1
trainer: tonic.Trainer()
