agent: tonic.tensorflow.agents.SAC()
environment: tonic.environments.ControlSuite('walker-run')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 8
sequential: 1
trainer: tonic.Trainer()
