agent: tonic.tensorflow.agents.PPO()
environment: tonic.environments.Bullet('CartPoleContinuousBulletEnv-v0')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 0
sequential: 1
trainer: tonic.Trainer()
