agent: tonic.tensorflow.agents.DDPG()
environment: tonic.environments.Gym('InvertedDoublePendulum-v2')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 8
sequential: 1
trainer: tonic.Trainer()
