agent: tonic.tensorflow.agents.TRPO()
environment: tonic.environments.Gym('Striker-v2')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 6
sequential: 1
trainer: tonic.Trainer()
