agent: tonic.tensorflow.agents.A2C()
environment: tonic.environments.ControlSuite('humanoid-stand')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 6
sequential: 1
trainer: tonic.Trainer()
