agent: tonic.tensorflow.agents.A2C()
environment: tonic.environments.ControlSuite('cartpole-swingup')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 9
sequential: 1
trainer: tonic.Trainer()
