agent: tonic.tensorflow.agents.TD3()
environment: tonic.environments.ControlSuite('humanoid-walk')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 6
sequential: 1
trainer: tonic.Trainer()
