agent: tonic.tensorflow.agents.PPO()
environment: tonic.environments.Gym('BipedalWalkerHardcore-v3')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 3
sequential: 1
trainer: tonic.Trainer()
