agent: tonic.tensorflow.agents.SAC()
environment: tonic.environments.ControlSuite('hopper-stand')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 6
sequential: 1
trainer: tonic.Trainer()
