agent: tonic.tensorflow.agents.DDPG()
environment: tonic.environments.ControlSuite('fish-swim')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 9
sequential: 1
trainer: tonic.Trainer()
