agent: tonic.tensorflow.agents.TRPO()
environment: tonic.environments.ControlSuite('humanoid-walk')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 7
sequential: 1
trainer: tonic.Trainer()
