agent: tonic.tensorflow.agents.TD3()
environment: tonic.environments.ControlSuite('cheetah-run')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 4
sequential: 1
trainer: tonic.Trainer()
