agent: tonic.tensorflow.agents.A2C()
environment: tonic.environments.Gym('BipedalWalkerHardcore-v3')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 1
sequential: 1
trainer: tonic.Trainer()
