agent: tonic.tensorflow.agents.SAC()
environment: tonic.environments.Gym('Swimmer-v3')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 9
sequential: 1
trainer: tonic.Trainer()
