agent: tonic.tensorflow.agents.A2C()
environment: tonic.environments.ControlSuite('cartpole-two_poles')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 5
sequential: 1
trainer: tonic.Trainer()
