agent: tonic.tensorflow.agents.DDPG()
environment: tonic.environments.ControlSuite('humanoid-run')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 7
sequential: 1
trainer: tonic.Trainer()
