agent: tonic.tensorflow.agents.A2C()
environment: tonic.environments.Gym('Hopper-v3')
header: import tonic.tensorflow
name: null
parallel: 1
seed: 5
sequential: 1
trainer: tonic.Trainer(steps=5000000, epoch_steps=50000, save_steps=500000, test_episodes=5,
  show_progress=False)
