agent: tonic.tensorflow.agents.SAC()
environment: tonic.environments.ControlSuite('walker-stand')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 3
sequential: 1
trainer: tonic.Trainer()
