agent: tonic.tensorflow.agents.SAC()
environment: tonic.environments.ControlSuite('cartpole-balance')
experiment_name: null
header: import tonic.tensorflow
parallel: 1
seed: 2
sequential: 1
trainer: tonic.Trainer()
